language: csharp
os:
  - linux
  - osx
env:
  global:
    - Configuration=Release
    - ShortVersion=1.0.0
    - VersionSuffix=beta2
mono: latest
dotnet: 1.0.4
script:
 - set -e
 - cd build
 - ./build.sh