language: csharp
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3
env:
  global:
    - Configuration=Release
    - ShortVersion=1.0.0
mono: none
dotnet: 2.0.0
before_script:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; mkdir -p /usr/local/lib; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
script:
 - set -e
 - cd build
 - ./build.sh