language: csharp
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode8.3
env:
  global:
    - Configuration=Release
    - ShortVersion=1.0.0
    - VersionSuffix=
mono: latest
dotnet: 2.0.0
script:
 - set -e
 - cd build
 - ./build.sh