version: 1.0.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: 1.0
nuget:
  project_feed: true
build_script:
- cmd: >-
    call build\BuildSolution.bat

    call build\CreatePackages.bat
test_script:
- cmd: >-
    call build\RunTests.bat

    call build\CalculateCoverage.bat
artifacts:
- path: src\**\*.nupkg
deploy: off