version: 1.0.{build}
configuration: Release
platform: Any CPU
build_script:
- cmd: call build\BuildSolution.bat
test_script:
- cmd: >-
    call build\RunTests.bat

    call build\CalculateCoverage.bat
deploy: off