version: $(ShortVersion).{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(ShortVersion)-$(VersionSuffix)-build{build}
  package_version: '{version}'
environment:
  VersionSuffix: beta2
  ShortVersion: 1.0.0
nuget:
  project_feed: true
build_script:
- ps: >-
    cd build

    .\build.ps1 -target CalculateCoverage
artifacts:
- path: build\artifacts\*.nupkg